Logging facility changes
Logging messages were analyzed to give proper reasoning.

INFO: Informational
WARN: Warnings
ERROR: For catch blocks for now
CRITICAL: Unused
DEBUG: Debug helper
TRACE: Would help debug but it displays variable contents and some
deeper code.
ASSERT: Unused, but we should be using it.